
export enum ErrorCodes {
    UNKNOWN = 0,

    // specific codes
    INVALID_EMAIL = 401,
    INVALID_USERNAME = 402,
    EMAIL_NOT_UNIQUE = 403,
    USERNAME_NOT_UNIQUE = 404,
    INVALID_PASSWORD = 405,
    INVALID_PHONE_NUMBER = 406,
    PHONE_NUMBER_NOT_UNIQUE = 407,
    INVALID_POST_VISIBILITY = 408,
    INVALID_DEVICE_INFO = 409,
    INVALID_USERNAME_QUERY = 411,
    INVALID_USER_ID = 412,
    INVALID_VERIFICATION_CODE = 413,
    INVALID_VERIFICATION_TOKEN = 414,
    INVALID_PASSWORD_RESET_TOKEN = 415,
    INVALID_PASSWORD_RESET_TYPE = 416,
    DEVICE_ID_IS_REQUIRED = 417,
    
    INVALID_POST_MEDIA = 418,
    INVALID_POST_THUMBNAIL = 419,
    INVALID_POST_TAGS = 420,
    INVALID_POST_CAPTION = 421,
    INVALID_POST_LOCATION = 422,
    INVALID_POST_ID = 423,

    INVALID_DM_CONTENTS = 431,

    INVALID_CONNECTION_ID = 441,

    INVALID_COMMENT_PARENT_ID = 451,
    INVALID_COMMENT_VISIBLITY = 452,
    INVALID_COMMENT_CONTENTS = 453,
    INVALID_COMMENT_ID = 454,

    PHONE_NUMBER_VERIFICATION_ATTEMPTS_LIMIT_REACHED = 601,
    PHONE_NUMBER_VERIFICATION_MISSING = 602,

    // generic codes
    UNIQUE_VIOLATION = 801,
    IS_REQUIRED = 802,
    INVALID_VALUE = 803
}

export const buildJoiError = (code, message, field) => {
    return JSON.stringify({
        code,
        message,
        field,
    })
}